# features
qemu_enable_ahci=false
qemu_enable_serial_io=false
qemu_enable_vhd=false
qemu_enable_iso=false
qemu_enable_networking=false
qemu_enable_net_dump=false
qemu_force_debug=false

# networking
qemu_enable_networking_type="nat"
qemu_mac="52:54:00:12:34:56"
qemu_network_card="virtio-net-device"
qemu_network_dump_file_path="netdump.pcap"

# system
qemu_system_memory="1G"

# files
qemu_path_iso="build/VirtualReflectionsOS.iso"
qemu_path_vhd="test_disk.vhd"
qemu_path_kernel="build/VirtualReflectionsOS.bin"

# qemu generic
qemu_machine="virt,highmem=off"
qemu_exe="qemu-system-aarch64.exe"
qemu_cpu="cortex-a53"