# features
qemu_enable_ahci=true
qemu_enable_serial_io=true
qemu_enable_vhd=true
qemu_enable_iso=true
qemu_enable_networking=true
qemu_enable_net_dump=true
qemu_force_debug=false
qemu_use_uefi=true

# networking
qemu_enable_networking_type="nat"
qemu_mac="52:54:00:12:34:56"
qemu_network_card="rtl8139"
qemu_network_dump_file_path="netdump.pcap"

# system
qemu_system_memory="4G"

# files
qemu_path_iso="build/VirtualReflectionsOS.iso"
qemu_path_vhd="test_disk.vhd"