@startuml kernel diagram
title Kernel Diagram (Core) v1
' left to right direction

actor "User Basic" as user

node "Interrupt Manager" as im
node "Input Manager" as inputm
node "Processor Abstraction" as pa

interface "Serviced Interrupt" as si
interface "Screen" as screen
interface "Debug Port" as dbgport

interface "Network Card" as nc
interface "Keyboard" as kb

node "Crash Handler" as ch

package "Networking" as networking {
    component "Packet Handler" as npa
    collections "Network Stack" as nstack
    component "DHCP" as ndhcp
    component "DNS" as ndns
}

package "Virtual Threads" as vthreads {
    component "Interrupt Handler" as vthreadsih
    component "Scheduler" as vthreadssc
}

package "Device Driver" as devicedrivers {
    component "PS/2" as ddps2
    component "PIT" as ddpit
    component "VGA" as ddvga
    component "cmos" as ddcmos
    component "Intel e1000" as dde1000
    
    folder "Storage Driver" as ddstorage {
        component "ACHI"
        component "IDE"
    }
}

package "Drivers" as drivers {
    package "PIT Driver" as pitdriver {
        component "Interrupt Handler" as pitih
    }

    node "VGA Driver" as vgadriver
    node "Intel e1000 Driver" as e1000driver
}

package "Virtual File System" as vfs {
    component "I/O" as vfsio
}

package "Memory Mangement" as mm {
    component "Heap" as heap
    component "DMA" as dma
    component "Virtual Memory" as vmem
    component "Physical Memory" as pmem
}

package "Components" as components {
    component "ELF Parser"
    component "Multiboot Parser"
    component "SMBios Parser"
}

database db [
    VHD
    ----
    MBR(?)
    ----
    FAT32
]

user --> si
user <-- screen
user <-- dbgport
si --> pa
si <-- kb
si <-- nc
pa --> im
ch <-- pa
ch <--> im
im --> ddps2
ddps2 <--> inputm
e1000driver --> npa
npa --> nstack
nstack --> ndns
nstack --> ndhcp
im --> ddpit
im --> vthreadsih : (software int)
im --> dde1000
pitih --> vthreadssc
ddpit --> pitdriver
ddvga --> vgadriver
dde1000 --> e1000driver
drivers --> pa
pmem --> pa
dma --> vmem
heap --> vmem
vmem --> pmem
vthreads --> pa
vgadriver --> screen
ddstorage --> db
vfs --> ddstorage

@enduml
