name: build kernel

on:
  push:
    branches: [ "main" ]

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]
#   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build image
      run: docker build -t builder .

    - name: run image
      run: docker run --rm -v ${{ github.workspace }}:/root/env builder
